# Generated by Django 5.0.3 on 2024-03-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=120, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('slug', models.SlugField(unique=True, verbose_name='')),
                ('image', models.ImageField(blank=True, upload_to='products/images', verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='')),
            ],
        ),
    ]
